# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the Windows build: one .exe, no console window.

Mirrors build-deb.sh's payload rule -- assets/ holds 83 clips but the app only
ever opens the handful named in carozerra.py's CLIPS, so read that list out of
the source and bundle exactly those. Same reason as the .deb: the two can't
drift, and the exe doesn't carry ~10M of clips nothing opens.

Build:  pyinstaller --clean --noconfirm packaging/carozerra.spec
Output: dist/carozerra.exe
"""
import ast
import os
import re

ROOT = os.path.abspath(os.path.join(SPECPATH, os.pardir))

src = open(os.path.join(ROOT, "carozerra.py"), encoding="utf-8").read()
m = re.search(r"^CLIPS\s*=\s*(\[.*?\])", src, re.S | re.M)
if not m:
    raise SystemExit("carozerra.spec: could not find CLIPS in carozerra.py")
CLIPS = ast.literal_eval(m.group(1))
if not CLIPS:
    raise SystemExit("carozerra.spec: CLIPS came back empty")

# (source, dest-dir-inside-bundle) -- unpacked at run time under sys._MEIPASS,
# which carozerra.py's APP_DIR picks up.
datas = [(os.path.join(ROOT, "assets", "pioneer.png"), "assets")]
datas += [(os.path.join(ROOT, "assets", "clips", c), os.path.join("assets", "clips"))
          for c in CLIPS]

# generated by packaging/make-ico.py; optional so a plain local build still works
icon = os.path.join(SPECPATH, "carozerra.ico")
icon = icon if os.path.exists(icon) else None

a = Analysis(
    [os.path.join(ROOT, "carozerra.py")],
    pathex=[ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    # nothing in the app touches these; Pillow drags some in on its own
    excludes=["tkinter", "unittest", "pydoc", "matplotlib", "numpy.testing"],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="carozerra",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    # UPX shrinks the exe but is a reliable way to earn an antivirus false
    # positive, which an unsigned build can't afford
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    icon=icon,
)
